# Machine-specific display modules for iq-9075-evk.
# Appended after display-modules-common.conf on this machine.

# This configuration file is placed in '/etc/modules-load.d/'
# This file is meant for machine : 'iq-9075-evk'

# List of drivers to be installed
# SA8775P GPU clock controller
# SA8775P display clock controller
# eDP PHY driver

gpucc_sa8775p
dispcc0_sa8775p
phy_qcom_edp
