# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Allow PipeWire to access DMA-HEAP for system-wide daemon mode

[Service]
SupplementaryGroups=dmaheap
