## Move the BlueZ5 native backend's Telephony D-Bus service to the system
## bus, since no session bus is available when wireplumber.service runs
## in system-wide mode.
##
## Also register the service as org.ofono on the system bus, enabling
## ofono-compatible applications and test scripts to work with the
## native HFP backend without modification.
monitor.bluez.properties = {
  bluez5.telephony.use-system-bus = true
  bluez5.telephony.provide-ofono = true
}
