# Target-specific audio modules for iq-9075-evk (SA8775P / SC8280XP).
# Appended after audio-modules-common.conf on this machine.

# This configuration file is placed in '/etc/modules-load.d/'
# This file is meant for machine : 'iq-9075-evk'

snd-soc-dmic
snd-soc-hdmi-codec
snd-soc-sc8280xp
snd-soc-max98357a
