# Machine-specific camera modules for iq-9075-evk.
# Appended after camera-modules-common.conf on this machine.

# This configuration file is placed in '/etc/modules-load.d/'
# This file is meant for machine : 'iq-9075-evk'

# List of drivers to be installed :
# SA8775P camera clock controller
# QCS9100 / IQ9075 Spectra camera driver

camcc_sa8775p
camera_qcs9100
